services:
  mssql:
    attach: false
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    domainname: mssql
    hostname: mssql
    container_name: mssql
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    networks:
      mssqlnet:
        ipv4_address: 192.168.128.3

  script:
    container_name: my_script
    depends_on:
      - mssql
    environment:
      - DB_HOST=192.168.128.3
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD} 
      - DB_CONTEXT=${DB_CONTEXT}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_SHEET_RANGE=${GOOGLE_SHEET_RANGE}

    build:
      context: .
      tags:
        - "my:script"
    networks:
      mssqlnet:
        ipv4_address: 192.168.128.4

networks:
  mssqlnet:
    name: mssqlnet
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.128.0/24
