services:
  mssql:
    attach: false
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    domainname: mssql
    hostname: mssql
    container_name: mssql
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    networks:
      mssqlnet:
        ipv4_address: ${DB_ADDRESS:-192.168.0.4}

  script:
    container_name: my_script
    depends_on:
      - mssql
    environment:
      - DB_ADDRESS=${DB_ADDRESS:-192.168.0.4}
      - DB_USER=${DB_USER:-sa}
      - DB_NAME=${DB_NAME:-master}
      - DB_PASSWORD=${DB_PASSWORD} 
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_SHEET_RANGE=${GOOGLE_SHEET_RANGE:-A2:Q157}
    build:
      context: .
      tags:
        - "my:script"
    networks:
      mssqlnet:
        ipv4_address: ${DB_ADDRESS:-192.168.0.3}

networks:
  mssqlnet:
    name: mssqlnet
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET:-192.168.0.0/24}
